## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
copyright = "2023"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
publishDir = "public"

# Remote
baseURL = "https://cine.drewku.com"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-TNEDDW5TL7"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------


[Params]
  description = "Andrew Ku's Cinematic Journey"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
#  github = "https://github.com/drookoo/"
#  twitter = "https://twitter.com/drookoo"
  email = "hi@drewku.com"
  instagram = "https://instagram.com/polychromeworks"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]